//
//  WordDataBaseSpanish.swift
//  ABC4
//
//  Created by Davi Rodrigues on 24/03/16.
//  Copyright © 2016 Pedro Rodrigues Grijó. All rights reserved.
//

import UIKit

class WordDataBaseSpanish: NSObject {

    fileprivate static var dataBase: [Category] = [Category]()
    
    static func setDataBase() {
        self.dataBase = [
            Category(categoryId: 0, categoryName: "animals", words: [
                Word(word: "Abadejo", difficulty: "Easy"),
                Word(word: "Abalone ", difficulty: "Easy"),
                Word(word: "Abejarón", difficulty: "Easy"),
                Word(word: "Abejaruco", difficulty: "Easy"),
                Word(word: "Abeja", difficulty: "Easy"),
                Word(word: "Abejorro ", difficulty: "Easy"),
                Word(word: "Ácaro", difficulty: "Easy"),
                Word(word: "Acedía", difficulty: "Easy"),
                Word(word: "Acentor ", difficulty: "Easy"),
                Word(word: "Agamido ", difficulty: "Easy"),
                Word(word: "Águila ", difficulty: "Easy"),
                Word(word: "Alacrán ", difficulty: "Easy"),
                Word(word: "Albatros ", difficulty: "Easy"),
                Word(word: "Alce ", difficulty: "Easy"),
                Word(word: "Almeja ", difficulty: "Easy"),
                Word(word: "Alondra ", difficulty: "Easy"),
                Word(word: "Ánade Real ", difficulty: "Easy"),
                Word(word: "Anchoa", difficulty: "Easy"),
                Word(word: "Anémona de mar", difficulty: "Easy"),
                Word(word: "Anfioxo", difficulty: "Easy"),
                Word(word: "Angelote ", difficulty: "Easy"),
                Word(word: "Anguila ", difficulty: "Easy"),
                Word(word: "Antílope ", difficulty: "Easy"),
                Word(word: "Araña ", difficulty: "Easy"),
                Word(word: "Arenque ", difficulty: "Easy"),
                Word(word: "Armadillo", difficulty: "Easy"),
                Word(word: "Armiño ", difficulty: "Easy"),
                Word(word: "Asno", difficulty: "Easy"),
                Word(word: "Atún", difficulty: "Easy"),
                Word(word: "Avefría", difficulty: "Easy"),
                Word(word: "Avestruz", difficulty: "Easy"),
                Word(word: "Avetoro", difficulty: "Easy"),
                Word(word: "Avispa", difficulty: "Easy"),
                Word(word: "Babirusa", difficulty: "Easy"),
                Word(word: "Babosa", difficulty: "Easy"),
                Word(word: "Babuino", difficulty: "Easy"),
                Word(word: "Bacalao", difficulty: "Easy"),
                Word(word: "Ballena ", difficulty: "Easy"),
                Word(word: "Banteng ", difficulty: "Easy"),
                Word(word: "Barasinga", difficulty: "Easy"),
                Word(word: "Barracuda ", difficulty: "Easy"),
                Word(word: "Becada", difficulty: "Easy"),
                Word(word: "Beira", difficulty: "Easy"),
                Word(word: "Beluga", difficulty: "Easy"),
                Word(word: "Bengalí", difficulty: "Easy"),
                Word(word: "Bermejuela", difficulty: "Easy"),
                Word(word: "Berrendo", difficulty: "Easy"),
                Word(word: "Besugo ", difficulty: "Easy"),
                Word(word: "Bisbita", difficulty: "Easy"),
                Word(word: "Bisonte", difficulty: "Easy"),
                Word(word: "Blanquillo ", difficulty: "Easy"),
                Word(word: "Boa", difficulty: "Easy"),
                Word(word: "Bogavante", difficulty: "Easy"),
                Word(word: "Bongo", difficulty: "Easy"),
                Word(word: "Bonito ", difficulty: "Easy"),
                Word(word: "Bonobo", difficulty: "Easy"),
                Word(word: "Boto ", difficulty: "Easy"),
                Word(word: "Buey ", difficulty: "Easy"),
                Word(word: "Búfalo", difficulty: "Easy"),
                Word(word: "Búho", difficulty: "Easy"),
                Word(word: "Buitre", difficulty: "Easy"),
                Word(word: "Burro", difficulty: "Easy"),
                Word(word: "Caballo", difficulty: "Easy"),
                Word(word: "Caballito de mar", difficulty: "Easy"),
                Word(word: "Cacatúa", difficulty: "Easy"),
                Word(word: "Cachalote", difficulty: "Easy"),
                Word(word: "Calamón", difficulty: "Easy"),
                Word(word: "Camaleón", difficulty: "Easy"),
                Word(word: "Camello", difficulty: "Easy"),
                Word(word: "Canguro", difficulty: "Easy"),
                Word(word: "Canario", difficulty: "Easy"),
                Word(word: "Cangrejo ", difficulty: "Easy"),
                Word(word: "Caracol", difficulty: "Easy"),
                Word(word: "Castor ", difficulty: "Easy"),
                Word(word: "Cebra ", difficulty: "Easy"),
                Word(word: "Centollo", difficulty: "Easy"),
                Word(word: "Cerdo", difficulty: "Easy"),
                Word(word: "Chacal", difficulty: "Easy"),
                Word(word: "Chimpancé", difficulty: "Easy"),
                Word(word: "Chinchilla ", difficulty: "Easy"),
                Word(word: "Ciempiés", difficulty: "Easy"),
                Word(word: "Ciervo", difficulty: "Easy"),
                Word(word: "Cigala", difficulty: "Easy"),
                Word(word: "Cisne", difficulty: "Easy"),
                Word(word: "Cobaya ", difficulty: "Easy"),
                Word(word: "Cochinilla", difficulty: "Easy"),
                Word(word: "Cocodrilo", difficulty: "Easy"),
                Word(word: "Coendú", difficulty: "Easy"),
                Word(word: "Coipú", difficulty: "Easy"),
                Word(word: "Colibrí", difficulty: "Easy"),
                Word(word: "Comadreja", difficulty: "Easy"),
                Word(word: "Conejo", difficulty: "Easy"),
                Word(word: "Coral", difficulty: "Easy"),
                Word(word: "Coridora", difficulty: "Easy"),
                Word(word: "Cormorán", difficulty: "Easy"),
                Word(word: "Cóndor", difficulty: "Easy"),
                Word(word: "Cotorra ", difficulty: "Easy"),
                Word(word: "Coyote", difficulty: "Easy"),
                Word(word: "Damán", difficulty: "Easy"),
                Word(word: "Delfín ", difficulty: "Easy"),
                Word(word: "Diablo de Tasmania", difficulty: "Easy"),
                Word(word: "Dik-dik", difficulty: "Easy"),
                Word(word: "Dingo ", difficulty: "Easy"),
                Word(word: "Dragón de Komodo", difficulty: "Easy"),
                Word(word: "Dromedario", difficulty: "Easy"),
                Word(word: "Gacela", difficulty: "Easy"),
                Word(word: "Galápago", difficulty: "Easy"),
                Word(word: "Gallina", difficulty: "Easy"),
                Word(word: "Gallipato", difficulty: "Easy"),
                Word(word: "Gallo", difficulty: "Easy"),
                Word(word: "Gamba", difficulty: "Easy"),
                Word(word: "Ganso", difficulty: "Easy"),
                Word(word: "Garcilla", difficulty: "Easy"),
                Word(word: "Garrapata", difficulty: "Easy"),
                Word(word: "Garza", difficulty: "Easy"),
                Word(word: "Gato", difficulty: "Easy"),
                Word(word: "Gavilán ", difficulty: "Easy"),
                Word(word: "Glotón", difficulty: "Easy"),
                Word(word: "Golondrina", difficulty: "Easy"),
                Word(word: "Gorila", difficulty: "Easy"),
                Word(word: "Gorgojo", difficulty: "Easy"),
                Word(word: "Gorrión", difficulty: "Easy"),
                Word(word: "Grillo", difficulty: "Easy"),
                Word(word: "Grulla ", difficulty: "Easy"),
                Word(word: "Guepardo", difficulty: "Easy"),
                Word(word: "Mamut ", difficulty: "Easy"),
                Word(word: "Mandril", difficulty: "Easy"),
                Word(word: "Mantis religiosa", difficulty: "Easy"),
                Word(word: "Mapache", difficulty: "Easy"),
                Word(word: "Marabú", difficulty: "Easy"),
                Word(word: "Marabunta", difficulty: "Easy"),
                Word(word: "Mariposa", difficulty: "Easy"),
                Word(word: "Marmota", difficulty: "Easy"),
                Word(word: "Medusa ", difficulty: "Easy"),
                Word(word: "Mejillón", difficulty: "Easy"),
                Word(word: "Milpiés", difficulty: "Easy"),
                Word(word: "Mofeta", difficulty: "Easy"),
                Word(word: "Mono", difficulty: "Easy"),
                Word(word: "Mosca ", difficulty: "Easy"),
                Word(word: "Mosquito", difficulty: "Easy"),
                Word(word: "Morsa", difficulty: "Easy"),
                Word(word: "Murciélago", difficulty: "Easy"),
                Word(word: "Pájaro ", difficulty: "Easy"),
                Word(word: "Paloma ", difficulty: "Easy"),
                Word(word: "Pantera", difficulty: "Easy"),
                Word(word: "Papagayo ", difficulty: "Easy"),
                Word(word: "Pelicano", difficulty: "Easy"),
                Word(word: "Perca", difficulty: "Easy"),
                Word(word: "Perdiz", difficulty: "Easy"),
                Word(word: "Perezoso", difficulty: "Easy"),
                Word(word: "Perico", difficulty: "Easy"),
                Word(word: "Peripato", difficulty: "Easy"),
                Word(word: "Periquito", difficulty: "Easy"),
                Word(word: "Perro ", difficulty: "Easy"),
                Word(word: "Petirrojo ", difficulty: "Easy"),
                Word(word: "Pez ", difficulty: "Easy"),
                Word(word: "Pingüino", difficulty: "Easy"),
                Word(word: "Pinzón", difficulty: "Easy"),
                Word(word: "Piojo ", difficulty: "Easy"),
                Word(word: "Piquituerto ", difficulty: "Easy"),
                Word(word: "Polilla ", difficulty: "Easy"),
                Word(word: "Puercoespín", difficulty: "Easy"),
                Word(word: "Pulga", difficulty: "Easy"),
                Word(word: "Pulpo", difficulty: "Easy"),
                Word(word: "Puma", difficulty: "Easy"),
                Word(word: "Tábano ", difficulty: "Easy"),
                Word(word: "Tejón", difficulty: "Easy"),
                Word(word: "Tenia", difficulty: "Easy"),
                Word(word: "Termita", difficulty: "Easy"),
                Word(word: "Tiburón", difficulty: "Easy"),
                Word(word: "Tigre", difficulty: "Easy"),
                Word(word: "Tijereta ", difficulty: "Easy"),
                Word(word: "Topo", difficulty: "Easy"),
                Word(word: "Toro", difficulty: "Easy"),
                Word(word: "Tortuga", difficulty: "Easy"),
                Word(word: "Tritón ", difficulty: "Easy"),
                Word(word: "Trucha", difficulty: "Easy"),
                Word(word: "Tucán", difficulty: "Easy")
                ]),
            
            Category(categoryId: 1, categoryName: "fruits", words: [
                Word(word: "Arándano", difficulty: "Easy"),
                Word(word: "Frambuesa", difficulty: "Easy"),
                Word(word: "Fresa", difficulty: "Easy"),
                Word(word: "Grosella espinosa", difficulty: "Easy"),
                Word(word: "Grosella negra", difficulty: "Easy"),
                Word(word: "Grosella roja", difficulty: "Easy"),
                Word(word: "Zarzamora", difficulty: "Easy"),
                Word(word: "Limón", difficulty: "Easy"),
                Word(word: "Mandarina", difficulty: "Easy"),
                Word(word: "Naranja", difficulty: "Easy"),
                Word(word: "Pomelo", difficulty: "Easy"),
                Word(word: "Melón", difficulty: "Easy"),
                Word(word: "Sandía", difficulty: "Easy"),
                Word(word: "Aguacate", difficulty: "Easy"),
                Word(word: "Carambola", difficulty: "Easy"),
                Word(word: "Chirimoya", difficulty: "Easy"),
                Word(word: "Coco", difficulty: "Easy"),
                Word(word: "Dátil", difficulty: "Easy"),
                Word(word: "Fruta de la pasión", difficulty: "Easy"),
                Word(word: "Kiwi", difficulty: "Easy"),
                Word(word: "Litchi", difficulty: "Easy"),
                Word(word: "Mango", difficulty: "Easy"),
                Word(word: "Papaya", difficulty: "Easy"),
                Word(word: "Piña", difficulty: "Easy"),
                Word(word: "Plátano", difficulty: "Easy"),
                Word(word: "Albaricoque", difficulty: "Easy"),
                Word(word: "Cereza", difficulty: "Easy"),
                Word(word: "Ciruela", difficulty: "Easy"),
                Word(word: "Higo", difficulty: "Easy"),
                Word(word: "Kaki", difficulty: "Easy"),
                Word(word: "Manzana", difficulty: "Easy"),
                Word(word: "Melocotón", difficulty: "Easy"),
                Word(word: "Nectarina", difficulty: "Easy"),
                Word(word: "Níspero", difficulty: "Easy"),
                Word(word: "Pera", difficulty: "Easy"),
                Word(word: "Uva", difficulty: "Easy"),
                Word(word: "Almendra", difficulty: "Easy"),
                Word(word: "Avellana", difficulty: "Easy"),
                Word(word: "Cacahuete", difficulty: "Easy"),
                Word(word: "Castaña", difficulty: "Easy"),
                Word(word: "Nuez", difficulty: "Easy"),
                Word(word: "Pacana", difficulty: "Easy"),
                Word(word: "Pistacho", difficulty: "Easy")
                ]),
            
            Category(categoryId: 2, categoryName: "adverbs", words: [
                Word(word: "ahora", difficulty: "Easy"),
                Word(word: "antes", difficulty: "Easy"),
                Word(word: "después", difficulty: "Easy"),
                Word(word: "tarde", difficulty: "Easy"),
                Word(word: "luego", difficulty: "Easy"),
                Word(word: "ayer", difficulty: "Easy"),
                Word(word: "temprano", difficulty: "Easy"),
                Word(word: "ya", difficulty: "Easy"),
                Word(word: "todavía", difficulty: "Easy"),
                Word(word: "anteayer", difficulty: "Easy"),
                Word(word: "aún", difficulty: "Easy"),
                Word(word: "pronto", difficulty: "Easy"),
                Word(word: "hoy", difficulty: "Easy"),
                Word(word: "aquí", difficulty: "Easy"),
                Word(word: "ahí", difficulty: "Easy"),
                Word(word: "allí", difficulty: "Easy"),
                Word(word: "cerca", difficulty: "Easy"),
                Word(word: "lejos", difficulty: "Easy"),
                Word(word: "fuera", difficulty: "Easy"),
                Word(word: "dentro", difficulty: "Easy"),
                Word(word: "alrededor", difficulty: "Easy"),
                Word(word: "aparte", difficulty: "Easy"),
                Word(word: "encima", difficulty: "Easy"),
                Word(word: "debajo", difficulty: "Easy"),
                Word(word: "delante", difficulty: "Easy"),
                Word(word: "detrás", difficulty: "Easy"),
                Word(word: "así", difficulty: "Easy"),
                Word(word: "bien", difficulty: "Easy"),
                Word(word: "mal", difficulty: "Easy"),
                Word(word: "despacio", difficulty: "Easy"),
                Word(word: "deprisa", difficulty: "Easy"),
                Word(word: "como", difficulty: "Easy"),
                Word(word: "mucho", difficulty: "Easy"),
                Word(word: "poco", difficulty: "Easy"),
                Word(word: "muy", difficulty: "Easy"),
                Word(word: "casi", difficulty: "Easy"),
                Word(word: "todo", difficulty: "Easy"),
                Word(word: "nada", difficulty: "Easy"),
                Word(word: "algo", difficulty: "Easy"),
                Word(word: "medio", difficulty: "Easy"),
                Word(word: "demasiado", difficulty: "Easy"),
                Word(word: "bastante", difficulty: "Easy"),
                Word(word: "más", difficulty: "Easy"),
                Word(word: "menos", difficulty: "Easy"),
                Word(word: "además", difficulty: "Easy"),
                Word(word: "incluso", difficulty: "Easy"),
                Word(word: "también", difficulty: "Easy"),
                Word(word: "sí", difficulty: "Easy"),
                Word(word: "también", difficulty: "Easy"),
                Word(word: "asimismo", difficulty: "Easy"),
                Word(word: "no", difficulty: "Easy"),
                Word(word: "tampoco", difficulty: "Easy"),
                Word(word: "jamás", difficulty: "Easy"),
                Word(word: "nunca", difficulty: "Easy")
                ]),
            
            Category(categoryId: 3, categoryName: "collectives", words: [
                Word(word: "Pavero", difficulty: "Easy"),
                Word(word: "Pelotón", difficulty: "Easy"),
                Word(word: "Plumerío", difficulty: "Easy"),
                Word(word: "Profesorado", difficulty: "Easy"),
                Word(word: "Población", difficulty: "Easy"),
                Word(word: "Pueblo", difficulty: "Easy"),
                Word(word: "Reparto", difficulty: "Easy"),
                Word(word: "Rebaño", difficulty: "Easy"),
                Word(word: "Ramo", difficulty: "Easy"),
                Word(word: "Secta", difficulty: "Easy"),
                Word(word: "Síndrome", difficulty: "Easy"),
                Word(word: "Tarjetero", difficulty: "Easy"),
                Word(word: "Tropa", difficulty: "Easy"),
                Word(word: "Turba", difficulty: "Easy"),
                Word(word: "Vajilla", difficulty: "Easy"),
                Word(word: "Vocabulario", difficulty: "Easy"),
                Word(word: "Yunta", difficulty: "Easy"),
                Word(word: "Agenda", difficulty: "Easy"),
                Word(word: "Artillería", difficulty: "Easy"),
                Word(word: "Asociación", difficulty: "Easy"),
                Word(word: "Aparato", difficulty: "Easy"),
                Word(word: "Alumnado", difficulty: "Easy"),
                Word(word: "Bandada", difficulty: "Easy"),
                Word(word: "Banda", difficulty: "Easy"),
                Word(word: "Biblioteca", difficulty: "Easy"),
                Word(word: "Borreguero", difficulty: "Easy"),
                Word(word: "Bosque", difficulty: "Easy"),
                Word(word: "Botín", difficulty: "Easy"),
                Word(word: "Colección", difficulty: "Easy"),
                Word(word: "Colonia", difficulty: "Easy"),
                Word(word: "Constelación", difficulty: "Easy"),
                Word(word: "Colmena", difficulty: "Easy"),
                Word(word: "Comando", difficulty: "Easy"),
                Word(word: "Continente", difficulty: "Easy"),
                Word(word: "Complejo", difficulty: "Easy"),
                Word(word: "Cónclave", difficulty: "Easy"),
                Word(word: "Conejero", difficulty: "Easy"),
                Word(word: "Confederación", difficulty: "Easy"),
                Word(word: "Caballada", difficulty: "Easy"),
                Word(word: "Caballería", difficulty: "Easy"),
                Word(word: "Camada", difficulty: "Easy"),
                Word(word: "Cardumen", difficulty: "Easy"),
                Word(word: "Caserío", difficulty: "Easy"),
                Word(word: "Clan", difficulty: "Easy"),
                Word(word: "Cámara", difficulty: "Easy"),
                Word(word: "Cementerio", difficulty: "Easy"),
                Word(word: "Cristalería", difficulty: "Easy"),
                Word(word: "Conejero", difficulty: "Easy"),
                Word(word: "Cubertería", difficulty: "Easy"),
                Word(word: "Dentadura", difficulty: "Easy"),
                Word(word: "Despensa", difficulty: "Easy"),
                Word(word: "Estatuto", difficulty: "Easy"),
                Word(word: "Ejército", difficulty: "Easy"),
                Word(word: "Enjambre", difficulty: "Easy"),
                Word(word: "Enciclopedia", difficulty: "Easy"),
                Word(word: "Directorio", difficulty: "Easy"),
                Word(word: "Drenaje", difficulty: "Easy"),
                Word(word: "Estacionamiento", difficulty: "Easy"),
                Word(word: "Estado", difficulty: "Easy"),
                Word(word: "Estatuto", difficulty: "Easy"),
                Word(word: "Equipo", difficulty: "Easy"),
                Word(word: "Escuadrón", difficulty: "Easy"),
                Word(word: "Flota", difficulty: "Easy"),
                Word(word: "Formulario", difficulty: "Easy"),
                Word(word: "Familia", difficulty: "Easy"),
                Word(word: "Federación", difficulty: "Easy"),
                Word(word: "Filmoteca", difficulty: "Easy"),
                Word(word: "Flota", difficulty: "Easy"),
                Word(word: "Fonoteca", difficulty: "Easy"),
                Word(word: "Galería", difficulty: "Easy"),
                Word(word: "Gallinero", difficulty: "Easy"),
                Word(word: "Gentío", difficulty: "Easy"),
                Word(word: "Gremio", difficulty: "Easy"),
                Word(word: "Grupo", difficulty: "Easy"),
                Word(word: "Guerrilla", difficulty: "Easy"),
                Word(word: "Guía", difficulty: "Easy"),
                Word(word: "Hormiguero", difficulty: "Easy")
                ]),
            
            Category(categoryId: 4, categoryName: "adjectives", words: [
                Word(word: "peligroso ", difficulty: "Easy"),
                Word(word: "verdadero ", difficulty: "Easy"),
                Word(word: "aburrido ", difficulty: "Easy"),
                Word(word: "activo ", difficulty: "Easy"),
                Word(word: "agradable ", difficulty: "Easy"),
                Word(word: "agradecido ", difficulty: "Easy"),
                Word(word: "barato ", difficulty: "Easy"),
                Word(word: "bonito ", difficulty: "Easy"),
                Word(word: "bueno ", difficulty: "Easy"),
                Word(word: "caliente ", difficulty: "Easy"),
                Word(word: "cariñoso ", difficulty: "Easy"),
                Word(word: "cerrado ", difficulty: "Easy"),
                Word(word: "complicado ", difficulty: "Easy"),
                Word(word: "cordial ", difficulty: "Easy"),
                Word(word: "correcto ", difficulty: "Easy"),
                Word(word: "cortes ", difficulty: "Easy"),
                Word(word: "critico ", difficulty: "Easy"),
                Word(word: "cuidadoso ", difficulty: "Easy"),
                Word(word: "curioso ", difficulty: "Easy"),
                Word(word: "delgado ", difficulty: "Easy"),
                Word(word: "diferente ", difficulty: "Easy"),
                Word(word: "difícil ", difficulty: "Easy"),
                Word(word: "divertido ", difficulty: "Easy"),
                Word(word: "dulce ", difficulty: "Easy"),
                Word(word: "duro ", difficulty: "Easy"),
                Word(word: "especial ", difficulty: "Easy"),
                Word(word: "estupido ", difficulty: "Easy"),
                Word(word: "fácil ", difficulty: "Easy"),
                Word(word: "famoso ", difficulty: "Easy"),
                Word(word: "fantástico ", difficulty: "Easy"),
                Word(word: "fiable ", difficulty: "Easy"),
                Word(word: "flojo ", difficulty: "Easy"),
                Word(word: "frecuente ", difficulty: "Easy"),
                Word(word: "fresco ", difficulty: "Easy"),
                Word(word: "frío ", difficulty: "Easy"),
                Word(word: "honrado ", difficulty: "Easy"),
                Word(word: "sincero ", difficulty: "Easy"),
                Word(word: "importante ", difficulty: "Easy"),
                Word(word: "independiente ", difficulty: "Easy"),
                Word(word: "interesante ", difficulty: "Easy"),
                Word(word: "joven ", difficulty: "Easy"),
                Word(word: "lento ", difficulty: "Easy"),
                Word(word: "libre ", difficulty: "Easy"),
                Word(word: "limpio ", difficulty: "Easy"),
                Word(word: "listo ", difficulty: "Easy"),
                Word(word: "loco ", difficulty: "Easy"),
                Word(word: "malo ", difficulty: "Easy"),
                Word(word: "maravilloso ", difficulty: "Easy"),
                Word(word: "moderno ", difficulty: "Easy"),
                Word(word: "muerto ", difficulty: "Easy"),
                Word(word: "necesario ", difficulty: "Easy"),
                Word(word: "nervioso ", difficulty: "Easy"),
                Word(word: "obligatorio ", difficulty: "Easy"),
                Word(word: "original ", difficulty: "Easy"),
                Word(word: "picante ", difficulty: "Easy"),
                Word(word: "posible ", difficulty: "Easy"),
                Word(word: "practico ", difficulty: "Easy"),
                Word(word: "privado ", difficulty: "Easy"),
                Word(word: "probable ", difficulty: "Easy"),
                Word(word: "profundo ", difficulty: "Easy"),
                Word(word: "prohibido ", difficulty: "Easy"),
                Word(word: "puntual ", difficulty: "Easy"),
                Word(word: "raro ", difficulty: "Easy"),
                Word(word: "rico ", difficulty: "Easy"),
                Word(word: "sano ", difficulty: "Easy"),
                Word(word: "seguro ", difficulty: "Easy"),
                Word(word: "serio ", difficulty: "Easy"),
                Word(word: "simpático ", difficulty: "Easy"),
                Word(word: "sincero ", difficulty: "Easy"),
                Word(word: "social ", difficulty: "Easy"),
                Word(word: "solo ", difficulty: "Easy"),
                Word(word: "soltero ", difficulty: "Easy"),
                Word(word: "suave ", difficulty: "Easy"),
                Word(word: "todo ", difficulty: "Easy"),
                Word(word: "tonto ", difficulty: "Easy"),
                Word(word: "intranquilo ", difficulty: "Easy"),
                Word(word: "tranquilo ", difficulty: "Easy"),
                Word(word: "único ", difficulty: "Easy"),
                Word(word: "antipático ", difficulty: "Easy"),
                Word(word: "casual ", difficulty: "Easy"),
                Word(word: "Terrible ", difficulty: "Easy"),
                Word(word: "Elegante ", difficulty: "Easy"),
                Word(word: "pesimista ", difficulty: "Easy"),
                Word(word: "idealista ", difficulty: "Easy"),
                Word(word: "realista ", difficulty: "Easy"),
                Word(word: "egoista ", difficulty: "Easy"),
                Word(word: "vago ", difficulty: "Easy"),
                Word(word: "comprensivo ", difficulty: "Easy"),
                Word(word: "desordenado ", difficulty: "Easy"),
                Word(word: "Competitivo ", difficulty: "Easy"),
                Word(word: "sarcástico ", difficulty: "Easy"),
                Word(word: "persuasivo ", difficulty: "Easy"),
                Word(word: "hilarante ", difficulty: "Easy"),
                Word(word: "orgulloso ", difficulty: "Easy"),
                Word(word: "numerofílico ", difficulty: "Easy"),
                Word(word: "perfeccionista ", difficulty: "Easy"),
                Word(word: "delicioso ", difficulty: "Easy"),
                Word(word: "perezoso ", difficulty: "Easy"),
                Word(word: "castroso ", difficulty: "Easy"),
                Word(word: "brillante ", difficulty: "Easy"),
                Word(word: "riesgoso ", difficulty: "Easy"),
                Word(word: "defensivo", difficulty: "Easy"),
                Word(word: "tolerante ", difficulty: "Easy"),
                Word(word: "tolerable", difficulty: "Easy"),
                Word(word: "impaciente ", difficulty: "Easy"),
                Word(word: "imponente", difficulty: "Easy"),
                Word(word: "imposible ", difficulty: "Easy"),
                Word(word: "repetitivo ", difficulty: "Easy"),
                Word(word: "inteligente", difficulty: "Easy"),
                Word(word: "irrepetible ", difficulty: "Easy"),
                Word(word: "arrogante ", difficulty: "Easy"),
                Word(word: "objetivo ", difficulty: "Easy"),
                Word(word: "sincero ", difficulty: "Easy"),
                Word(word: "fantasmal ", difficulty: "Easy"),
                Word(word: "frío ", difficulty: "Easy"),
                Word(word: "serio ", difficulty: "Easy"),
                Word(word: "caliente ", difficulty: "Easy"),
                Word(word: "alegre ", difficulty: "Easy"),
                Word(word: "tonto ", difficulty: "Easy"),
                Word(word: "chistoso ", difficulty: "Easy"),
                Word(word: "analítico ", difficulty: "Easy"),
                Word(word: "contagioso ", difficulty: "Easy"),
                Word(word: "retraido", difficulty: "Easy"),
                Word(word: "fanático", difficulty: "Easy"),
                Word(word: "extraterrestre ", difficulty: "Easy"),
                Word(word: "fiel ", difficulty: "Easy"),
                Word(word: "optimista ", difficulty: "Easy"),
                Word(word: "gentil ", difficulty: "Easy"),
                Word(word: "puro ", difficulty: "Easy"),
                Word(word: "amoroso ", difficulty: "Easy"),
                Word(word: "egocentrico ", difficulty: "Easy"),
                Word(word: "radiante ", difficulty: "Easy"),
                Word(word: "creativo ", difficulty: "Easy"),
                Word(word: "eficiente", difficulty: "Easy"),
                Word(word: "dedicado ", difficulty: "Easy"),
                Word(word: "anticultural ", difficulty: "Easy"),
                Word(word: "estadístico ", difficulty: "Easy"),
                Word(word: "literal ", difficulty: "Easy"),
                Word(word: "figurado ", difficulty: "Easy"),
                Word(word: "heterosexual ", difficulty: "Easy"),
                Word(word: "antojadizo ", difficulty: "Easy"),
                Word(word: "meticuloso ", difficulty: "Easy"),
                Word(word: "no melindroso ", difficulty: "Easy"),
                Word(word: "respetuoso ", difficulty: "Easy"),
                Word(word: "repetitivo ", difficulty: "Easy"),
                Word(word: "exquisito. ", difficulty: "Easy"),
                Word(word: "irreprimible ", difficulty: "Easy"),
                Word(word: "imperdonable ", difficulty: "Easy"),
                Word(word: "indomito ", difficulty: "Easy"),
                Word(word: "desvergonzado ", difficulty: "Easy"),
                Word(word: "egoista ", difficulty: "Easy"),
                Word(word: "contumaz ", difficulty: "Easy"),
                Word(word: "desalmado ", difficulty: "Easy"),
                Word(word: "furioso ", difficulty: "Easy"),
                Word(word: "voluble ", difficulty: "Easy"),
                Word(word: "intrepido", difficulty: "Easy")
                ]),
            
            Category(categoryId: 5, categoryName: "coins", words: [
                Word(word: "Afegane", difficulty: "Easy"),
                Word(word: "Bólivar", difficulty: "Easy"),
                Word(word: "Cedi", difficulty: "Easy"),
                Word(word: "Coroa", difficulty: "Easy"),
                Word(word: "Dalasi", difficulty: "Easy"),
                Word(word: "Dinar", difficulty: "Easy"),
                Word(word: "Dólar", difficulty: "Easy"),
                Word(word: "Dram", difficulty: "Easy"),
                Word(word: "Euro", difficulty: "Easy"),
                Word(word: "Florim", difficulty: "Easy"),
                Word(word: "Franco", difficulty: "Easy"),
                Word(word: "Grívnia", difficulty: "Easy"),
                Word(word: "Guarani", difficulty: "Easy"),
                Word(word: "Gurde", difficulty: "Easy"),
                Word(word: "Iene", difficulty: "Easy"),
                Word(word: "Yuan", difficulty: "Easy"),
                Word(word: "Kina", difficulty: "Easy"),
                Word(word: "Kip", difficulty: "Easy"),
                Word(word: "Kuna", difficulty: "Easy"),
                Word(word: "Kwacha", difficulty: "Easy"),
                Word(word: "Kwanza", difficulty: "Easy"),
                Word(word: "Kyat", difficulty: "Easy"),
                Word(word: "Lari", difficulty: "Easy"),
                Word(word: "Leu", difficulty: "Easy"),
                Word(word: "Lev", difficulty: "Easy"),
                Word(word: "Libra", difficulty: "Easy"),
                Word(word: "Lira", difficulty: "Easy"),
                Word(word: "Litas", difficulty: "Easy"),
                Word(word: "Loti", difficulty: "Easy"),
                Word(word: "Manat", difficulty: "Easy"),
                Word(word: "Naira", difficulty: "Easy"),
                Word(word: "Nakfa", difficulty: "Easy"),
                Word(word: "Ngultrum", difficulty: "Easy"),
                Word(word: "Novo sol", difficulty: "Easy"),
                Word(word: "Pataca", difficulty: "Easy"),
                Word(word: "Peso", difficulty: "Easy"),
                Word(word: "Real", difficulty: "Easy"),
                Word(word: "Rial", difficulty: "Easy"),
                Word(word: "Riel", difficulty: "Easy"),
                Word(word: "Ringuite", difficulty: "Easy"),
                Word(word: "Rublo", difficulty: "Easy"),
                Word(word: "Rupia", difficulty: "Easy"),
                Word(word: "Tala", difficulty: "Easy"),
                Word(word: "Tengue", difficulty: "Easy"),
                Word(word: "Tugrik", difficulty: "Easy"),
                Word(word: "Vatu", difficulty: "Easy"),
                Word(word: "Won", difficulty: "Easy"),
                Word(word: "Xelim", difficulty: "Easy"),
                Word(word: "Zloty", difficulty: "Easy")
                ]),
            
            Category(categoryId: 6, categoryName: "clothes", words: [
                Word(word: "Cinturón", difficulty: "Easy"),
                Word(word: "Guante", difficulty: "Easy"),
                Word(word: "Casco", difficulty: "Easy"),
                Word(word: "Camisa", difficulty: "Easy"),
                Word(word: "Pantalón", difficulty: "Easy"),
                Word(word: "Sombrero", difficulty: "Easy"),
                Word(word: "Chaqueta", difficulty: "Easy"),
                Word(word: "Vaqueros", difficulty: "Easy"),
                Word(word: "Capuchón", difficulty: "Easy"),
                Word(word: "Vestido", difficulty: "Easy"),
                Word(word: "Cuello", difficulty: "Easy"),
                Word(word: "Corbata", difficulty: "Easy"),
                Word(word: "Babero", difficulty: "Easy"),
                Word(word: "Pantalón", difficulty: "Easy"),
                Word(word: "Leggings", difficulty: "Easy"),
                Word(word: "Abrigo", difficulty: "Easy"),
                Word(word: "Minifalda", difficulty: "Easy"),
                Word(word: "Gorro", difficulty: "Easy"),
                Word(word: "Camisón", difficulty: "Easy"),
                Word(word: "Picardías", difficulty: "Easy"),
                Word(word: "Pendiente", difficulty: "Easy"),
                Word(word: "Overol", difficulty: "Easy"),
                Word(word: "Pantufla", difficulty: "Easy"),
                Word(word: "Abrigo de piel", difficulty: "Easy"),
                Word(word: "Peluca", difficulty: "Easy"),
                Word(word: "Gorra", difficulty: "Easy"),
                Word(word: "Suéter", difficulty: "Easy"),
                Word(word: "Falda", difficulty: "Easy"),
                Word(word: "Sandalias", difficulty: "Easy"),
                Word(word: "Pijama", difficulty: "Easy"),
                Word(word: "Patín", difficulty: "Easy"),
                Word(word: "Cordón", difficulty: "Easy"),
                Word(word: "Delantal", difficulty: "Easy"),
                Word(word: "Calcetín", difficulty: "Easy"),
                Word(word: "Zapato", difficulty: "Easy"),
                Word(word: "Bota", difficulty: "Easy"),
                Word(word: "Pelele", difficulty: "Easy"),
                Word(word: "Rebeca", difficulty: "Easy"),
                Word(word: "Calceta", difficulty: "Easy"),
                Word(word: "Medias", difficulty: "Easy"),
                Word(word: "Camiseta", difficulty: "Easy"),
                Word(word: "Traje de buzo", difficulty: "Easy"),
                Word(word: "Uniforme", difficulty: "Easy"),
                Word(word: "Bividí", difficulty: "Easy"),
                Word(word: "Calzoncillos", difficulty: "Easy"),
                Word(word: "Chaleco", difficulty: "Easy"),
                Word(word: "Pañal", difficulty: "Easy"),
                Word(word: "Camisa", difficulty: "Easy"),
                Word(word: "Sombrero", difficulty: "Easy")
                ]),
            
            Category(categoryId: 7, categoryName: "home appliances", words: [
                Word(word: "Abrebotes", difficulty: "Easy"),
                Word(word: "Abrelatas", difficulty: "Easy"),
                Word(word: "Abreostras", difficulty: "Easy"),
                Word(word: "Abretapas", difficulty: "Easy"),
                Word(word: "Abridor", difficulty: "Easy"),
                Word(word: "Aceitera", difficulty: "Easy"),
                Word(word: "Accesorio para ravioli", difficulty: "Easy"),
                Word(word: "Adapatador", difficulty: "Easy"),
                Word(word: "Inducción-Vitrocerámica", difficulty: "Easy"),
                Word(word: "Afilador", difficulty: "Easy"),
                Word(word: "Aguja de bridar", difficulty: "Easy"),
                Word(word: "Aireador de vino", difficulty: "Easy"),
                Word(word: "Alisador fondant", difficulty: "Easy"),
                Word(word: "Anillo antigoteo", difficulty: "Easy"),
                Word(word: "Anillas niveladoras", difficulty: "Easy"),
                Word(word: "Aros de presentacion", difficulty: "Easy"),
                Word(word: "Asador de manzanas", difficulty: "Easy"),
                Word(word: "Asador de pollos", difficulty: "Easy"),
                Word(word: "Azucarero", difficulty: "Easy"),
                Word(word: "Bajoplato", difficulty: "Easy"),
                Word(word: "Bandejas", difficulty: "Easy"),
                Word(word: "Bandeja de mantequilla", difficulty: "Easy"),
                Word(word: "Bandeja de horno", difficulty: "Easy"),
                Word(word: "Báscula de cocina", difficulty: "Easy"),
                Word(word: "Bases", difficulty: "Easy"),
                Word(word: "Baterías de cocina", difficulty: "Easy"),
                Word(word: "Batidor", difficulty: "Easy"),
                Word(word: "Biberones", difficulty: "Easy"),
                Word(word: "Blonda", difficulty: "Easy"),
                Word(word: "Bol", difficulty: "Easy"),
                Word(word: "Bola de cocer arroz", difficulty: "Easy"),
                Word(word: "Bolas de hielo", difficulty: "Easy"),
                Word(word: "Bolas de te", difficulty: "Easy"),
                Word(word: "Bola para especias", difficulty: "Easy"),
                Word(word: "Bolas de repostería", difficulty: "Easy"),
                Word(word: "Bolsa enfriabotellas", difficulty: "Easy"),
                Word(word: "Bolsa para grill", difficulty: "Easy"),
                Word(word: "Bolsas para asar", difficulty: "Easy"),
                Word(word: "Bomba de vacio", difficulty: "Easy"),
                Word(word: "Boquillas", difficulty: "Easy"),
                Word(word: "Bote de residuos", difficulty: "Easy"),
                Word(word: "Brochetas", difficulty: "Easy"),
                Word(word: "Buñolera", difficulty: "Easy"),
                Word(word: "Cacerolas", difficulty: "Easy"),
                Word(word: "Cacerolas tradicionales", difficulty: "Easy"),
                Word(word: "Cacerola para horno", difficulty: "Easy"),
                Word(word: "Cacerola de vapor", difficulty: "Easy"),
                Word(word: "Cacillo", difficulty: "Easy"),
                Word(word: "Cacillo de aceitunas", difficulty: "Easy"),
                Word(word: "Cadena de peso", difficulty: "Easy"),
                Word(word: "Cafeteras", difficulty: "Easy"),
                Word(word: "Cafetera cónica", difficulty: "Easy"),
                Word(word: "Cafetera de émbolo", difficulty: "Easy"),
                Word(word: "Cafetera express", difficulty: "Easy"),
                Word(word: "Cafetera pava", difficulty: "Easy"),
                Word(word: "Cafetera silbante", difficulty: "Easy"),
                Word(word: "Cafetera turca", difficulty: "Easy"),
                Word(word: "Cajas para cupcakes", difficulty: "Easy"),
                Word(word: "Cantimplora", difficulty: "Easy"),
                Word(word: "Cápsulas", difficulty: "Easy"),
                Word(word: "Cápsula bombón", difficulty: "Easy"),
                Word(word: "Cápsula madalena", difficulty: "Easy"),
                Word(word: "Cápsula cupcake", difficulty: "Easy"),
                Word(word: "Cargas para sifón", difficulty: "Easy"),
                Word(word: "Cascanueces", difficulty: "Easy"),
                Word(word: "Cazo", difficulty: "Easy"),
                Word(word: "Cazo tradicional", difficulty: "Easy"),
                Word(word: "Cazo de baño María", difficulty: "Easy"),
                Word(word: "Cazo freidor", difficulty: "Easy"),
                Word(word: "Cazuela guisera", difficulty: "Easy"),
                Word(word: "Cazuelita (para servir)", difficulty: "Easy"),
                Word(word: "Centrifugadora de ensalada y verduras", difficulty: "Easy"),
                Word(word: "Cepillos", difficulty: "Easy"),
                Word(word: "Cepillo limpiacornetes", difficulty: "Easy"),
                Word(word: "Cepillo limpiador de botellas", difficulty: "Easy"),
                Word(word: "Cepillo para cacerolas", difficulty: "Easy"),
                Word(word: "Cepillo para verduras", difficulty: "Easy"),
                Word(word: "Cestillos", difficulty: "Easy"),
                Word(word: "Cestillo de vapor", difficulty: "Easy"),
                Word(word: "Cestillo freidor", difficulty: "Easy"),
                Word(word: "Churrera", difficulty: "Easy"),
                Word(word: "Cocotte", difficulty: "Easy"),
                Word(word: "Coctelera", difficulty: "Easy"),
                Word(word: "Colador", difficulty: "Easy"),
                Word(word: "Colgador mural", difficulty: "Easy"),
                Word(word: "Comprobador de tartas", difficulty: "Easy"),
                Word(word: "Contenedores", difficulty: "Easy"),
                Word(word: "Cortacápsulas", difficulty: "Easy"),
                Word(word: "Cortadores", difficulty: "Easy"),
                Word(word: "Cortador de donuts", difficulty: "Easy"),
                Word(word: "Cortador de foie", difficulty: "Easy"),
                Word(word: "Cortador de láminas", difficulty: "Easy"),
                Word(word: "Cortador de limones", difficulty: "Easy"),
                Word(word: "Cortador de manzanas", difficulty: "Easy"),
                Word(word: "Cortador de melón y piñas", difficulty: "Easy"),
                Word(word: "Cortador de raviolis", difficulty: "Easy"),
                Word(word: "Cortador de verduras", difficulty: "Easy"),
                Word(word: "Cortador en virutas", difficulty: "Easy"),
                Word(word: "Cortahuevos", difficulty: "Easy"),
                Word(word: "Cortamasas", difficulty: "Easy"),
                Word(word: "Cortapastas", difficulty: "Easy"),
                Word(word: "Cortapatatas", difficulty: "Easy"),
                Word(word: "Cortapiñas", difficulty: "Easy"),
                Word(word: "Cortapizza", difficulty: "Easy"),
                Word(word: "Cortaquesos", difficulty: "Easy"),
                Word(word: "Cubiertos", difficulty: "Easy"),
                Word(word: "Cubitera", difficulty: "Easy"),
                Word(word: "Cubo", difficulty: "Easy"),
                Word(word: "Cubo de champán", difficulty: "Easy"),
                Word(word: "Cucharas", difficulty: "Easy"),
                Word(word: "Cuchara de mesa", difficulty: "Easy"),
                Word(word: "cuchara de medidas", difficulty: "Easy"),
                Word(word: "Cuchara de pasta", difficulty: "Easy"),
                Word(word: "Cuchara de té", difficulty: "Easy"),
                Word(word: "Cucharilla de Cocktail", difficulty: "Easy"),
                Word(word: "Cucharrillas de presentación", difficulty: "Easy"),
                Word(word: "Cuchillas", difficulty: "Easy"),
                Word(word: "Cuchillos", difficulty: "Easy"),
                Word(word: "Descapsulador", difficulty: "Easy"),
                Word(word: "Descorazonador", difficulty: "Easy"),
                Word(word: "Desgranador", difficulty: "Easy"),
                Word(word: "Deshuesador de cerezas", difficulty: "Easy"),
                Word(word: "Dispensadores", difficulty: "Easy"),
                Word(word: "Dispensador de azúcar", difficulty: "Easy"),
                Word(word: "Dispensador de Cápsulas", difficulty: "Easy"),
                Word(word: "dispensador de helado", difficulty: "Easy"),
                Word(word: "Dispensador de miel", difficulty: "Easy"),
                Word(word: "Dispensador de queso", difficulty: "Easy"),
                Word(word: "Dosificador", difficulty: "Easy"),
                Word(word: "Elimina-grasas", difficulty: "Easy"),
                Word(word: "Encendedor", difficulty: "Easy"),
                Word(word: "Enfriabotellas", difficulty: "Easy"),
                Word(word: "Envase de vacío", difficulty: "Easy"),
                Word(word: "Envoltorio para cupcake", difficulty: "Easy"),
                Word(word: "Embudos", difficulty: "Easy"),
                Word(word: "Empanadera", difficulty: "Easy"),
                Word(word: "Emulsionador", difficulty: "Easy"),
                Word(word: "Escalfador", difficulty: "Easy"),
                Word(word: "Escanciador", difficulty: "Easy"),
                Word(word: "Escurrecubiertos", difficulty: "Easy"),
                Word(word: "Escurridor", difficulty: "Easy"),
                Word(word: "Espaciadores de platos", difficulty: "Easy"),
                Word(word: "Espátulas", difficulty: "Easy"),
                Word(word: "Espátula de repostería", difficulty: "Easy"),
                Word(word: "Especiero", difficulty: "Easy"),
                Word(word: "Espolvoreador", difficulty: "Easy"),
                Word(word: "Esponja limpiadora de sifones", difficulty: "Easy"),
                Word(word: "Espumaderas", difficulty: "Easy"),
                Word(word: "Estecas", difficulty: "Easy"),
                Word(word: "Estuche de vapor", difficulty: "Easy"),
                Word(word: "Etiquetas para vino", difficulty: "Easy"),
                Word(word: "Exprimidores", difficulty: "Easy"),
                Word(word: "Fiambrera", difficulty: "Easy"),
                Word(word: "Filtros", difficulty: "Easy"),
                Word(word: "Flanero/flanera", difficulty: "Easy"),
                Word(word: "Fondant", difficulty: "Easy"),
                Word(word: "Fondue", difficulty: "Easy"),
                Word(word: "Freidora", difficulty: "Easy"),
                Word(word: "Frutero", difficulty: "Easy"),
                Word(word: "Gafas", difficulty: "Easy"),
                Word(word: "Grasera", difficulty: "Easy"),
                Word(word: "Grill", difficulty: "Easy"),
                Word(word: "Guardaverduras", difficulty: "Easy"),
                Word(word: "Guías", difficulty: "Easy"),
                Word(word: "Harinero", difficulty: "Easy"),
                Word(word: "Heladeras", difficulty: "Easy"),
                Word(word: "Hiladores", difficulty: "Easy"),
                Word(word: "Hilo de cocina", difficulty: "Easy"),
                Word(word: "Identificadores", difficulty: "Easy"),
                Word(word: "Infusor", difficulty: "Easy"),
                Word(word: "Inyector", difficulty: "Easy"),
                Word(word: "Jarras", difficulty: "Easy"),
                Word(word: "Jarras de servir", difficulty: "Easy"),
                Word(word: "Jarras de mesa", difficulty: "Easy"),
                Word(word: "Jarras medidoras", difficulty: "Easy"),
                Word(word: "Juego de vino", difficulty: "Easy"),
                Word(word: "Lámina antiadherente", difficulty: "Easy"),
                Word(word: "Prensador de ajos", difficulty: "Easy"),
                Word(word: "Lechera", difficulty: "Easy"),
                Word(word: "Liras", difficulty: "Easy"),
                Word(word: "Macerador", difficulty: "Easy"),
                Word(word: "Maletín portalimentos", difficulty: "Easy"),
                Word(word: "Malla para carne", difficulty: "Easy"),
                Word(word: "Mandolina de cocina", difficulty: "Easy"),
                Word(word: "Manga de repostería", difficulty: "Easy"),
                Word(word: "Manopla", difficulty: "Easy"),
                Word(word: "Máquina de pasta fresca", difficulty: "Easy"),
                Word(word: "Marcadores", difficulty: "Easy"),
                Word(word: "Marcador de galletas", difficulty: "Easy"),
                Word(word: "Marcador de panes", difficulty: "Easy"),
                Word(word: "Marcador de tartas", difficulty: "Easy"),
                Word(word: "Mechador", difficulty: "Easy"),
                Word(word: "Medidor de licor", difficulty: "Easy"),
                Word(word: "Medidor de Spaguetti", difficulty: "Easy"),
                Word(word: "Mezclador de masas", difficulty: "Easy"),
                Word(word: "Moldes", difficulty: "Easy"),
                Word(word: "Moldes de gofres", difficulty: "Easy"),
                Word(word: "Moldes de cupcake", difficulty: "Easy"),
                Word(word: "Molde Savarín", difficulty: "Easy"),
                Word(word: "Molinillos", difficulty: "Easy"),
                Word(word: "Molinillo de pimienta", difficulty: "Easy"),
                Word(word: "Molinillo de café", difficulty: "Easy"),
                Word(word: "Mortero de cocina", difficulty: "Easy"),
                Word(word: "Olla", difficulty: "Easy"),
                Word(word: "Olla de vapor", difficulty: "Easy"),
                Word(word: "Paellera", difficulty: "Easy"),
                Word(word: "Palangana", difficulty: "Easy"),
                Word(word: "Palas", difficulty: "Easy"),
                Word(word: "Pala de pescado", difficulty: "Easy"),
                Word(word: "Pala para pizza", difficulty: "Easy"),
                Word(word: "Pala de espaguetti", difficulty: "Easy"),
                Word(word: "Pala para tartas", difficulty: "Easy"),
                Word(word: "Palilos", difficulty: "Easy"),
                Word(word: "Palos para piruletas", difficulty: "Easy"),
                Word(word: "Panera", difficulty: "Easy"),
                Word(word: "Papel para horno", difficulty: "Easy"),
                Word(word: "Papillotes", difficulty: "Easy"),
                Word(word: "Parrilla", difficulty: "Easy"),
                Word(word: "Pasador de frutas", difficulty: "Easy"),
                Word(word: "Pasapurés", difficulty: "Easy"),
                Word(word: "Pasatomates", difficulty: "Easy"),
                Word(word: "Peladores", difficulty: "Easy"),
                Word(word: "Pela-ajos", difficulty: "Easy"),
                Word(word: "Pelador de espárragos", difficulty: "Easy"),
                Word(word: "Pelador de naranjas", difficulty: "Easy"),
                Word(word: "Pelamanzanas", difficulty: "Easy"),
                Word(word: "Pelapatatas", difficulty: "Easy"),
                Word(word: "Pelatomates", difficulty: "Easy"),
                Word(word: "Petaca", difficulty: "Easy"),
                Word(word: "Picador", difficulty: "Easy"),
                Word(word: "Pico vertedor", difficulty: "Easy"),
                Word(word: "Piedra para pizza", difficulty: "Easy"),
                Word(word: "Pincel", difficulty: "Easy"),
                Word(word: "Pinzas", difficulty: "Easy"),
                Word(word: "Pisador", difficulty: "Easy"),
                Word(word: "Plato", difficulty: "Easy"),
                Word(word: "Portautensilios", difficulty: "Easy"),
                Word(word: "Pote", difficulty: "Easy"),
                Word(word: "Prensa-ajos", difficulty: "Easy"),
                Word(word: "Prensa-latas", difficulty: "Easy"),
                Word(word: "Prensa-patatas", difficulty: "Easy"),
                Word(word: "Protector de dedos", difficulty: "Easy"),
                Word(word: "Quemador", difficulty: "Easy"),
                Word(word: "Rabanera", difficulty: "Easy"),
                Word(word: "Racionador de helado", difficulty: "Easy"),
                Word(word: "Rallador", difficulty: "Easy"),
                Word(word: "Ramequín", difficulty: "Easy"),
                Word(word: "Rasqueta", difficulty: "Easy"),
                Word(word: "Rasqueta vitrocerámica", difficulty: "Easy"),
                Word(word: "Recogemigas", difficulty: "Easy"),
                Word(word: "Recogeverduras", difficulty: "Easy"),
                Word(word: "Rejilla", difficulty: "Easy"),
                Word(word: "Reposa-teteras", difficulty: "Easy"),
                Word(word: "Reposa-utensilios", difficulty: "Easy"),
                Word(word: "Rociador de salsas", difficulty: "Easy"),
                Word(word: "Rodillos", difficulty: "Easy"),
                Word(word: "Rodillo de amasar", difficulty: "Easy"),
                Word(word: "Rodillo de repostería", difficulty: "Easy"),
                Word(word: "Rodillo mirayas", difficulty: "Easy"),
                Word(word: "Rodillo nivelador", difficulty: "Easy"),
                Word(word: "Rodillo punteador", difficulty: "Easy"),
                Word(word: "Rodillo de rombos", difficulty: "Easy"),
                Word(word: "Rodillo para croissant", difficulty: "Easy"),
                Word(word: "Rollo de PVC", difficulty: "Easy"),
                Word(word: "Rompemarisco", difficulty: "Easy"),
                Word(word: "Rosquillera", difficulty: "Easy"),
                Word(word: "Ruleta cortapasta", difficulty: "Easy"),
                Word(word: "Rustidera", difficulty: "Easy"),
                Word(word: "Sacacorchos", difficulty: "Easy"),
                Word(word: "Sacapuntas", difficulty: "Easy"),
                Word(word: "Saco de legumbres", difficulty: "Easy"),
                Word(word: "Saco para jamón", difficulty: "Easy"),
                Word(word: "Salero-Pimentero", difficulty: "Easy"),
                Word(word: "Salsera", difficulty: "Easy"),
                Word(word: "Salva-asas", difficulty: "Easy"),
                Word(word: "Salvamangos", difficulty: "Easy"),
                Word(word: "Salvamantel", difficulty: "Easy")
                ]),
            
            Category(categoryId: 8, categoryName: "countries", words: [
                Word(word: "Afganistán", difficulty: "Easy"),
                Word(word: "Albania", difficulty: "Easy"),
                Word(word: "Alemania", difficulty: "Easy"),
                Word(word: "Andorra", difficulty: "Easy"),
                Word(word: "Angola", difficulty: "Easy"),
                Word(word: "Antigua y Barbuda", difficulty: "Easy"),
                Word(word: "Arabia Saudita", difficulty: "Easy"),
                Word(word: "Argelia", difficulty: "Easy"),
                Word(word: "Argentina", difficulty: "Easy"),
                Word(word: "Armenia", difficulty: "Easy"),
                Word(word: "Australia", difficulty: "Easy"),
                Word(word: "Austria", difficulty: "Easy"),
                Word(word: "Azerbaiyán", difficulty: "Easy"),
                Word(word: "Bahamas", difficulty: "Easy"),
                Word(word: "Bangladés", difficulty: "Easy"),
                Word(word: "Barbados", difficulty: "Easy"),
                Word(word: "Baréin", difficulty: "Easy"),
                Word(word: "Bélgica", difficulty: "Easy"),
                Word(word: "Belice", difficulty: "Easy"),
                Word(word: "Benín", difficulty: "Easy"),
                Word(word: "Bielorrusia", difficulty: "Easy"),
                Word(word: "Birmania", difficulty: "Easy"),
                Word(word: "Bolivia", difficulty: "Easy"),
                Word(word: "Bosnia y Herzegovina", difficulty: "Easy"),
                Word(word: "Botsuana", difficulty: "Easy"),
                Word(word: "Brasil", difficulty: "Easy"),
                Word(word: "Brunéi", difficulty: "Easy"),
                Word(word: "Bulgaria", difficulty: "Easy"),
                Word(word: "Burkina Faso", difficulty: "Easy"),
                Word(word: "Burundi", difficulty: "Easy"),
                Word(word: "Bután", difficulty: "Easy"),
                Word(word: "Cabo Verde", difficulty: "Easy"),
                Word(word: "Camboya", difficulty: "Easy"),
                Word(word: "Camerún", difficulty: "Easy"),
                Word(word: "Canadá", difficulty: "Easy"),
                Word(word: "Catar", difficulty: "Easy"),
                Word(word: "Chad", difficulty: "Easy"),
                Word(word: "Chile", difficulty: "Easy"),
                Word(word: "China", difficulty: "Easy"),
                Word(word: "Chipre", difficulty: "Easy"),
                Word(word: "Ciudad del Vaticano", difficulty: "Easy"),
                Word(word: "Colombia", difficulty: "Easy"),
                Word(word: "Comoras", difficulty: "Easy"),
                Word(word: "Corea del Norte", difficulty: "Easy"),
                Word(word: "Corea del Sur", difficulty: "Easy"),
                Word(word: "Costa de Marfil", difficulty: "Easy"),
                Word(word: "Costa Rica", difficulty: "Easy"),
                Word(word: "Croacia", difficulty: "Easy"),
                Word(word: "Cuba", difficulty: "Easy"),
                Word(word: "Dinamarca", difficulty: "Easy"),
                Word(word: "Dominica", difficulty: "Easy"),
                Word(word: "Ecuador", difficulty: "Easy"),
                Word(word: "Egipto", difficulty: "Easy"),
                Word(word: "El Salvador", difficulty: "Easy"),
                Word(word: "Emiratos Árabes Unidos", difficulty: "Easy"),
                Word(word: "Eritrea", difficulty: "Easy"),
                Word(word: "Eslovaquia", difficulty: "Easy"),
                Word(word: "Eslovenia", difficulty: "Easy"),
                Word(word: "España", difficulty: "Easy"),
                Word(word: "Estados Unidos", difficulty: "Easy"),
                Word(word: "Estonia", difficulty: "Easy"),
                Word(word: "Etiopía", difficulty: "Easy"),
                Word(word: "Filipinas", difficulty: "Easy"),
                Word(word: "Finlandia", difficulty: "Easy"),
                Word(word: "Fiyi", difficulty: "Easy"),
                Word(word: "Francia", difficulty: "Easy"),
                Word(word: "Gabón", difficulty: "Easy"),
                Word(word: "Gambia", difficulty: "Easy"),
                Word(word: "Georgia", difficulty: "Easy"),
                Word(word: "Ghana", difficulty: "Easy"),
                Word(word: "Granada", difficulty: "Easy"),
                Word(word: "Grecia", difficulty: "Easy"),
                Word(word: "Guatemala", difficulty: "Easy"),
                Word(word: "Guyana", difficulty: "Easy"),
                Word(word: "Guinea", difficulty: "Easy"),
                Word(word: "Guinea ecuatorial", difficulty: "Easy"),
                Word(word: "Guinea-Bisáu", difficulty: "Easy"),
                Word(word: "Haití", difficulty: "Easy"),
                Word(word: "Honduras", difficulty: "Easy"),
                Word(word: "Hungría", difficulty: "Easy"),
                Word(word: "India", difficulty: "Easy"),
                Word(word: "Indonesia", difficulty: "Easy"),
                Word(word: "Irak", difficulty: "Easy"),
                Word(word: "Irán", difficulty: "Easy"),
                Word(word: "Irlanda", difficulty: "Easy"),
                Word(word: "Islandia", difficulty: "Easy"),
                Word(word: "Islas Marshall", difficulty: "Easy"),
                Word(word: "Islas Salomón", difficulty: "Easy"),
                Word(word: "Israel", difficulty: "Easy"),
                Word(word: "Italia", difficulty: "Easy"),
                Word(word: "Jamaica", difficulty: "Easy"),
                Word(word: "Japón", difficulty: "Easy"),
                Word(word: "Jordania", difficulty: "Easy"),
                Word(word: "Kazajistán", difficulty: "Easy"),
                Word(word: "Kenia", difficulty: "Easy"),
                Word(word: "Kirguistán", difficulty: "Easy"),
                Word(word: "Kiribati", difficulty: "Easy"),
                Word(word: "Kuwait", difficulty: "Easy"),
                Word(word: "Laos", difficulty: "Easy"),
                Word(word: "Lesoto", difficulty: "Easy"),
                Word(word: "Letonia", difficulty: "Easy"),
                Word(word: "Líbano", difficulty: "Easy"),
                Word(word: "Liberia", difficulty: "Easy"),
                Word(word: "Libia", difficulty: "Easy"),
                Word(word: "Liechtenstein", difficulty: "Easy"),
                Word(word: "Lituania", difficulty: "Easy"),
                Word(word: "Luxemburgo", difficulty: "Easy"),
                Word(word: "Madagascar", difficulty: "Easy"),
                Word(word: "Malasia", difficulty: "Easy"),
                Word(word: "Malaui", difficulty: "Easy"),
                Word(word: "Maldivas", difficulty: "Easy"),
                Word(word: "Malí", difficulty: "Easy"),
                Word(word: "Malta", difficulty: "Easy"),
                Word(word: "Marruecos", difficulty: "Easy"),
                Word(word: "Mauricio", difficulty: "Easy"),
                Word(word: "Mauritania", difficulty: "Easy"),
                Word(word: "México", difficulty: "Easy"),
                Word(word: "Micronesia", difficulty: "Easy"),
                Word(word: "Moldavia", difficulty: "Easy"),
                Word(word: "Mónaco", difficulty: "Easy"),
                Word(word: "Mongolia", difficulty: "Easy"),
                Word(word: "Montenegro", difficulty: "Easy"),
                Word(word: "Mozambique", difficulty: "Easy"),
                Word(word: "Namibia", difficulty: "Easy"),
                Word(word: "Nauru", difficulty: "Easy"),
                Word(word: "Nepal", difficulty: "Easy"),
                Word(word: "Nicaragua", difficulty: "Easy"),
                Word(word: "Níger", difficulty: "Easy"),
                Word(word: "Nigeria", difficulty: "Easy"),
                Word(word: "Noruega", difficulty: "Easy"),
                Word(word: "Nueva Zelanda", difficulty: "Easy"),
                Word(word: "Omán", difficulty: "Easy"),
                Word(word: "Países Bajos", difficulty: "Easy"),
                Word(word: "Pakistán", difficulty: "Easy"),
                Word(word: "Palaos", difficulty: "Easy"),
                Word(word: "Panamá", difficulty: "Easy"),
                Word(word: "Papúa Nueva Guinea", difficulty: "Easy"),
                Word(word: "Paraguay", difficulty: "Easy"),
                Word(word: "Perú", difficulty: "Easy"),
                Word(word: "Polonia", difficulty: "Easy"),
                Word(word: "Portugal", difficulty: "Easy"),
                Word(word: "Reino Unido", difficulty: "Easy"),
                Word(word: "República Centroafricana", difficulty: "Easy"),
                Word(word: "República Checa", difficulty: "Easy"),
                Word(word: "República de Macedonia", difficulty: "Easy"),
                Word(word: "República del Congo", difficulty: "Easy"),
                Word(word: "República Democrática del Congo", difficulty: "Easy"),
                Word(word: "República Dominicana", difficulty: "Easy"),
                Word(word: "República Sudafricana", difficulty: "Easy"),
                Word(word: "Ruanda", difficulty: "Easy"),
                Word(word: "Rumanía", difficulty: "Easy"),
                Word(word: "Rusia", difficulty: "Easy"),
                Word(word: "Samoa", difficulty: "Easy"),
                Word(word: "San Cristóbal y Nieves", difficulty: "Easy"),
                Word(word: "San Marino", difficulty: "Easy"),
                Word(word: "San Vicente y las Granadinas", difficulty: "Easy"),
                Word(word: "Santa Lucía", difficulty: "Easy"),
                Word(word: "Santo Tomé y Príncipe", difficulty: "Easy"),
                Word(word: "Senegal", difficulty: "Easy"),
                Word(word: "Serbia", difficulty: "Easy"),
                Word(word: "Seychelles", difficulty: "Easy"),
                Word(word: "Sierra Leona", difficulty: "Easy"),
                Word(word: "Singapur", difficulty: "Easy"),
                Word(word: "Siria", difficulty: "Easy"),
                Word(word: "Somalia", difficulty: "Easy"),
                Word(word: "Sri Lanka", difficulty: "Easy"),
                Word(word: "Suazilandia", difficulty: "Easy"),
                Word(word: "Sudán", difficulty: "Easy"),
                Word(word: "Sudán del Sur", difficulty: "Easy"),
                Word(word: "Suecia", difficulty: "Easy"),
                Word(word: "Suiza", difficulty: "Easy"),
                Word(word: "Surinam", difficulty: "Easy"),
                Word(word: "Tailandia", difficulty: "Easy"),
                Word(word: "Tanzania", difficulty: "Easy"),
                Word(word: "Tayikistán", difficulty: "Easy"),
                Word(word: "Timor Oriental", difficulty: "Easy"),
                Word(word: "Togo", difficulty: "Easy"),
                Word(word: "Tonga", difficulty: "Easy"),
                Word(word: "Trinidad y Tobago", difficulty: "Easy"),
                Word(word: "Túnez", difficulty: "Easy"),
                Word(word: "Turkmenistán", difficulty: "Easy"),
                Word(word: "Turquía", difficulty: "Easy"),
                Word(word: "Tuvalu", difficulty: "Easy"),
                Word(word: "Ucrania", difficulty: "Easy"),
                Word(word: "Uganda", difficulty: "Easy"),
                Word(word: "Uruguay", difficulty: "Easy"),
                Word(word: "Uzbekistán", difficulty: "Easy"),
                Word(word: "Vanuatu", difficulty: "Easy"),
                Word(word: "Venezuela", difficulty: "Easy"),
                Word(word: "Vietnam", difficulty: "Easy"),
                Word(word: "Yemen", difficulty: "Easy"),
                Word(word: "Yibuti", difficulty: "Easy"),
                Word(word: "Zambia", difficulty: "Easy"),
                Word(word: "Zimbabue", difficulty: "Easy")
                ]),
            
            Category(categoryId: 9, categoryName: "martial arts", words: [
                Word(word: "Aikido", difficulty: "Easy"),
                Word(word: "Boxe", difficulty: "Easy"),
                Word(word: "Capoeira", difficulty: "Easy"),
                Word(word: "Esgrima", difficulty: "Easy"),
                Word(word: "Jiu-Jitsu", difficulty: "Easy"),
                Word(word: "Judô", difficulty: "Easy"),
                Word(word: "Karate", difficulty: "Easy"),
                Word(word: "Kickboxing", difficulty: "Easy"),
                Word(word: "Krav Maga", difficulty: "Easy"),
                Word(word: "Kung Fu", difficulty: "Easy"),
                Word(word: "Muay Thai", difficulty: "Easy"),
                Word(word: "Ninjutsu", difficulty: "Easy"),
                Word(word: "Sambo", difficulty: "Easy"),
                Word(word: "Savate", difficulty: "Easy"),
                Word(word: "Taekwondo", difficulty: "Easy"),
                Word(word: "Wrestling", difficulty: "Easy")
                ]),
            
            Category(categoryId: 10, categoryName: "flowers", words: [
                Word(word: "Agapanthus", difficulty: "Easy"),
                Word(word: "Agrostemma", difficulty: "Easy"),
                Word(word: "Allium", difficulty: "Easy"),
                Word(word: "Amarillis", difficulty: "Easy"),
                Word(word: "Anémona", difficulty: "Easy"),
                Word(word: "Anthurium", difficulty: "Easy"),
                Word(word: "Caléndula", difficulty: "Easy"),
                Word(word: "Campanula", difficulty: "Easy"),
                Word(word: "Celosía", difficulty: "Easy"),
                Word(word: "Clavel", difficulty: "Easy"),
                Word(word: "Rosa", difficulty: "Easy"),
                Word(word: "Crisantemo", difficulty: "Easy"),
                Word(word: "Dalia", difficulty: "Easy"),
                Word(word: "Gardenia", difficulty: "Easy"),
                Word(word: "Girasol", difficulty: "Easy")
                ]),
            
        ]

    }
    
    static func getDataBase()->[Category] {
        return self.dataBase
    }
    
}
